### ISSUE TITLE
Information about the training and testing file

### ISSUE THREAD

**Issue by rukhmamir** [sanmin0312/P2D#2]
Hi, Can you please share which file is required for training and testing the dataset?
as you have mentioned in the run.md file but I am unable to find the files or path  

**Train**

python [EXP_PATH] --amp_backend native -b 4 --gpus 4
**Evaluation**

python [EXP_PATH] --ckpt_path [CKPT_PATH] -e -b 4 --gpus 4

**Comment by sanmin0312** [comment]
Hi,

[EXP_PATH] is the path for the config file and [CKPT_PATH] is the trained weight file.
(During training, the weight is saved in ./output directory by default.)

Here is an example:

**Train**
python ./exps/nuscenes/p2d/p2d_deform_lss_r50_256x704_128x128_24e_3key.py --amp_backend native - b 4 --gpus 4

**Evaluation**
python ./exps/nuscenes/p2d/p2d_deform_lss_r50_256x704_128x128_24e_3key.py --ckpt_path ./outputs/p2d_deform_lss_r50_256x704_128x128_24e_3key/lightning_logs/version_0/23.pth - b 4 --gpus 4

**Comment by rukhmamir** [comment]
Hi, I am trying to run the file (the path path you have given ) for the training. but it is causing the error. even though files are correctly placed

`!python ./exps/nuscenes/p2d/p2d_deform_lss_r50_256x704_128x128_24e_3key.py --amp_backend native - b 4 --gpus 4`
```
Traceback (most recent call last):
  File "./exps/nuscenes/p2d/p2d_deform_lss_r50_256x704_128x128_24e_3key.py", line 3, in <module>
    from p2d.exps.base_cli import run_cli
ModuleNotFoundError: No module named 'p2d.exps
```

**Comment by sanmin0312** [comment]
Could you try follwings? 

**train**
python .p2d/exps/nuscenes/p2d/p2d_deform_lss_r50_256x704_128x128_24e_3key.py --amp_backend native - b 4 --gpus 4

test
python .p2d/exps/nuscenes/p2d/p2d_deform_lss_r50_256x704_128x128_24e_3key.py --ckpt_path ./outputs/p2d_deform_lss_r50_256x704_128x128_24e_3key/lightning_logs/version_0/23.pth -e - b 4 --gpus 4

**Comment by rukhmamir** [comment]
well, I have tried both but facing the same issue on both commands 

```
Traceback (most recent call last):
  File "p2d_deform_lss_r50_256x704_128x128_24e_3key.py", line 3, in <module>
    from p2d.exps.base_cli import run_cli
ModuleNotFoundError: No module named 'p2d.exps'

```

**Comment by sanmin0312** [comment]
Did you check your working directory?

**Comment by rukhmamir** [comment]
Yes, I'm currently working in the '\P2D\P2D\p2d' directory.

**Comment by sanmin0312** [comment]
I think the working directory should be /P2D/P2D. Can you try with this?

**Comment by rukhmamir** [comment]
Hi, I am attempting to run your code on the Linux operating system Ubuntu 24.04 LTS in Colab. While trying to train the dataset, I encountered the following issue:
![image](https://github.com/sanmin0312/P2D/assets/130539844/61fd7088-2eda-40d6-8a4d-490bd759a196)


I then attempted to update the relevant library, but the issue persists. The new issue is as follows:

![image](https://github.com/sanmin0312/P2D/assets/130539844/fb556165-0d91-47df-989a-9f7884c9e1d9)


Could you please provide insight into why I am facing these issues? Is it related to the operating system, or could there be another underlying cause? Additionally, could you recommend the most suitable operating system for running this code?
